/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BotBuilderRouteImport } from './routes/bot-builder'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QualityCenterRouteImport } from './routes/quality-center'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WebappsRouteImport } from './routes/webapps'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as ApiBotBuilderRouteImport } from './routes/api.bot-builder'
import { Route as ApiBotEditRouteImport } from './routes/api.bot-edit'
import { Route as ApiBotEnvioAutomaticoRouteImport } from './routes/api.bot-envio-automatico'
import { Route as ApiBotHealthRouteImport } from './routes/api.bot-health'
import { Route as ApiBotLifecycleRouteImport } from './routes/api.bot-lifecycle'
import { Route as ApiBotToggleRouteImport } from './routes/api.bot-toggle'
import { Route as ApiBotWhatsappRouteImport } from './routes/api.bot-whatsapp'
import { Route as ApiCatalogImportRouteImport } from './routes/api.catalog-import'
import { Route as ApiCatalogStockRouteImport } from './routes/api.catalog-stock'
import { Route as ApiClientAdminUserRouteImport } from './routes/api.client-admin-user'
import { Route as ApiCopilotRouteImport } from './routes/api.copilot'
import { Route as ApiImpersonateRouteImport } from './routes/api.impersonate'
import { Route as ApiMagicOnboardRouteImport } from './routes/api.magic-onboard'
import { Route as ApiProvisionStatusRouteImport } from './routes/api.provision-status'
import { Route as ApiQualityCenterRouteImport } from './routes/api.quality-center'
import { Route as ApiWebappFactoryRouteImport } from './routes/api.webapp-factory'
import { Route as ApiWebhooksLeadsRouteImport } from './routes/api.webhooks.leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BotBuilderRoute = BotBuilderRouteImport.update({
  id: '/bot-builder',
  path: '/bot-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityCenterRoute = QualityCenterRouteImport.update({
  id: '/quality-center',
  path: '/quality-center',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WebappsRoute = WebappsRouteImport.update({
  id: '/webapps',
  path: '/webapps',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotBuilderRoute = ApiBotBuilderRouteImport.update({
  id: '/api/bot-builder',
  path: '/api/bot-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotEditRoute = ApiBotEditRouteImport.update({
  id: '/api/bot-edit',
  path: '/api/bot-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotEnvioAutomaticoRoute = ApiBotEnvioAutomaticoRouteImport.update({
  id: '/api/bot-envio-automatico',
  path: '/api/bot-envio-automatico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotHealthRoute = ApiBotHealthRouteImport.update({
  id: '/api/bot-health',
  path: '/api/bot-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotLifecycleRoute = ApiBotLifecycleRouteImport.update({
  id: '/api/bot-lifecycle',
  path: '/api/bot-lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotToggleRoute = ApiBotToggleRouteImport.update({
  id: '/api/bot-toggle',
  path: '/api/bot-toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotWhatsappRoute = ApiBotWhatsappRouteImport.update({
  id: '/api/bot-whatsapp',
  path: '/api/bot-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogImportRoute = ApiCatalogImportRouteImport.update({
  id: '/api/catalog-import',
  path: '/api/catalog-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogStockRoute = ApiCatalogStockRouteImport.update({
  id: '/api/catalog-stock',
  path: '/api/catalog-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientAdminUserRoute = ApiClientAdminUserRouteImport.update({
  id: '/api/client-admin-user',
  path: '/api/client-admin-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImpersonateRoute = ApiImpersonateRouteImport.update({
  id: '/api/impersonate',
  path: '/api/impersonate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMagicOnboardRoute = ApiMagicOnboardRouteImport.update({
  id: '/api/magic-onboard',
  path: '/api/magic-onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvisionStatusRoute = ApiProvisionStatusRouteImport.update({
  id: '/api/provision-status',
  path: '/api/provision-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQualityCenterRoute = ApiQualityCenterRouteImport.update({
  id: '/api/quality-center',
  path: '/api/quality-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebappFactoryRoute = ApiWebappFactoryRouteImport.update({
  id: '/api/webapp-factory',
  path: '/api/webapp-factory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksLeadsRoute = ApiWebhooksLeadsRouteImport.update({
  id: '/api/webhooks/leads',
  path: '/api/webhooks/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bot-builder': typeof BotBuilderRoute
  '/clients': typeof ClientsRoute
  '/health': typeof HealthRoute
  '/leads': typeof LeadsRoute
  '/ledger': typeof LedgerRoute
  '/products': typeof ProductsRoute
  '/quality-center': typeof QualityCenterRoute
  '/settings': typeof SettingsRoute
  '/webapps': typeof WebappsRoute
  '/website': typeof WebsiteRoute
  '/api/bot-builder': typeof ApiBotBuilderRoute
  '/api/bot-edit': typeof ApiBotEditRoute
  '/api/bot-envio-automatico': typeof ApiBotEnvioAutomaticoRoute
  '/api/bot-health': typeof ApiBotHealthRoute
  '/api/bot-lifecycle': typeof ApiBotLifecycleRoute
  '/api/bot-toggle': typeof ApiBotToggleRoute
  '/api/bot-whatsapp': typeof ApiBotWhatsappRoute
  '/api/catalog-import': typeof ApiCatalogImportRoute
  '/api/catalog-stock': typeof ApiCatalogStockRoute
  '/api/client-admin-user': typeof ApiClientAdminUserRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/impersonate': typeof ApiImpersonateRoute
  '/api/magic-onboard': typeof ApiMagicOnboardRoute
  '/api/provision-status': typeof ApiProvisionStatusRoute
  '/api/quality-center': typeof ApiQualityCenterRoute
  '/api/webapp-factory': typeof ApiWebappFactoryRoute
  '/api/webhooks/leads': typeof ApiWebhooksLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bot-builder': typeof BotBuilderRoute
  '/clients': typeof ClientsRoute
  '/health': typeof HealthRoute
  '/leads': typeof LeadsRoute
  '/ledger': typeof LedgerRoute
  '/products': typeof ProductsRoute
  '/quality-center': typeof QualityCenterRoute
  '/settings': typeof SettingsRoute
  '/webapps': typeof WebappsRoute
  '/website': typeof WebsiteRoute
  '/api/bot-builder': typeof ApiBotBuilderRoute
  '/api/bot-edit': typeof ApiBotEditRoute
  '/api/bot-envio-automatico': typeof ApiBotEnvioAutomaticoRoute
  '/api/bot-health': typeof ApiBotHealthRoute
  '/api/bot-lifecycle': typeof ApiBotLifecycleRoute
  '/api/bot-toggle': typeof ApiBotToggleRoute
  '/api/bot-whatsapp': typeof ApiBotWhatsappRoute
  '/api/catalog-import': typeof ApiCatalogImportRoute
  '/api/catalog-stock': typeof ApiCatalogStockRoute
  '/api/client-admin-user': typeof ApiClientAdminUserRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/impersonate': typeof ApiImpersonateRoute
  '/api/magic-onboard': typeof ApiMagicOnboardRoute
  '/api/provision-status': typeof ApiProvisionStatusRoute
  '/api/quality-center': typeof ApiQualityCenterRoute
  '/api/webapp-factory': typeof ApiWebappFactoryRoute
  '/api/webhooks/leads': typeof ApiWebhooksLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bot-builder': typeof BotBuilderRoute
  '/clients': typeof ClientsRoute
  '/health': typeof HealthRoute
  '/leads': typeof LeadsRoute
  '/ledger': typeof LedgerRoute
  '/products': typeof ProductsRoute
  '/quality-center': typeof QualityCenterRoute
  '/settings': typeof SettingsRoute
  '/webapps': typeof WebappsRoute
  '/website': typeof WebsiteRoute
  '/api/bot-builder': typeof ApiBotBuilderRoute
  '/api/bot-edit': typeof ApiBotEditRoute
  '/api/bot-envio-automatico': typeof ApiBotEnvioAutomaticoRoute
  '/api/bot-health': typeof ApiBotHealthRoute
  '/api/bot-lifecycle': typeof ApiBotLifecycleRoute
  '/api/bot-toggle': typeof ApiBotToggleRoute
  '/api/bot-whatsapp': typeof ApiBotWhatsappRoute
  '/api/catalog-import': typeof ApiCatalogImportRoute
  '/api/catalog-stock': typeof ApiCatalogStockRoute
  '/api/client-admin-user': typeof ApiClientAdminUserRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/impersonate': typeof ApiImpersonateRoute
  '/api/magic-onboard': typeof ApiMagicOnboardRoute
  '/api/provision-status': typeof ApiProvisionStatusRoute
  '/api/quality-center': typeof ApiQualityCenterRoute
  '/api/webapp-factory': typeof ApiWebappFactoryRoute
  '/api/webhooks/leads': typeof ApiWebhooksLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bot-builder'
    | '/clients'
    | '/health'
    | '/leads'
    | '/ledger'
    | '/products'
    | '/quality-center'
    | '/settings'
    | '/webapps'
    | '/website'
    | '/api/bot-builder'
    | '/api/bot-edit'
    | '/api/bot-envio-automatico'
    | '/api/bot-health'
    | '/api/bot-lifecycle'
    | '/api/bot-toggle'
    | '/api/bot-whatsapp'
    | '/api/catalog-import'
    | '/api/catalog-stock'
    | '/api/client-admin-user'
    | '/api/copilot'
    | '/api/impersonate'
    | '/api/magic-onboard'
    | '/api/provision-status'
    | '/api/quality-center'
    | '/api/webapp-factory'
    | '/api/webhooks/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bot-builder'
    | '/clients'
    | '/health'
    | '/leads'
    | '/ledger'
    | '/products'
    | '/quality-center'
    | '/settings'
    | '/webapps'
    | '/website'
    | '/api/bot-builder'
    | '/api/bot-edit'
    | '/api/bot-envio-automatico'
    | '/api/bot-health'
    | '/api/bot-lifecycle'
    | '/api/bot-toggle'
    | '/api/bot-whatsapp'
    | '/api/catalog-import'
    | '/api/catalog-stock'
    | '/api/client-admin-user'
    | '/api/copilot'
    | '/api/impersonate'
    | '/api/magic-onboard'
    | '/api/provision-status'
    | '/api/quality-center'
    | '/api/webapp-factory'
    | '/api/webhooks/leads'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bot-builder'
    | '/clients'
    | '/health'
    | '/leads'
    | '/ledger'
    | '/products'
    | '/quality-center'
    | '/settings'
    | '/webapps'
    | '/website'
    | '/api/bot-builder'
    | '/api/bot-edit'
    | '/api/bot-envio-automatico'
    | '/api/bot-health'
    | '/api/bot-lifecycle'
    | '/api/bot-toggle'
    | '/api/bot-whatsapp'
    | '/api/catalog-import'
    | '/api/catalog-stock'
    | '/api/client-admin-user'
    | '/api/copilot'
    | '/api/impersonate'
    | '/api/magic-onboard'
    | '/api/provision-status'
    | '/api/quality-center'
    | '/api/webapp-factory'
    | '/api/webhooks/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BotBuilderRoute: typeof BotBuilderRoute
  ClientsRoute: typeof ClientsRoute
  HealthRoute: typeof HealthRoute
  LeadsRoute: typeof LeadsRoute
  LedgerRoute: typeof LedgerRoute
  ProductsRoute: typeof ProductsRoute
  QualityCenterRoute: typeof QualityCenterRoute
  SettingsRoute: typeof SettingsRoute
  WebappsRoute: typeof WebappsRoute
  WebsiteRoute: typeof WebsiteRoute
  ApiBotBuilderRoute: typeof ApiBotBuilderRoute
  ApiBotEditRoute: typeof ApiBotEditRoute
  ApiBotEnvioAutomaticoRoute: typeof ApiBotEnvioAutomaticoRoute
  ApiBotHealthRoute: typeof ApiBotHealthRoute
  ApiBotLifecycleRoute: typeof ApiBotLifecycleRoute
  ApiBotToggleRoute: typeof ApiBotToggleRoute
  ApiBotWhatsappRoute: typeof ApiBotWhatsappRoute
  ApiCatalogImportRoute: typeof ApiCatalogImportRoute
  ApiCatalogStockRoute: typeof ApiCatalogStockRoute
  ApiClientAdminUserRoute: typeof ApiClientAdminUserRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ApiImpersonateRoute: typeof ApiImpersonateRoute
  ApiMagicOnboardRoute: typeof ApiMagicOnboardRoute
  ApiProvisionStatusRoute: typeof ApiProvisionStatusRoute
  ApiQualityCenterRoute: typeof ApiQualityCenterRoute
  ApiWebappFactoryRoute: typeof ApiWebappFactoryRoute
  ApiWebhooksLeadsRoute: typeof ApiWebhooksLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-builder': {
      id: '/bot-builder'
      path: '/bot-builder'
      fullPath: '/bot-builder'
      preLoaderRoute: typeof BotBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-center': {
      id: '/quality-center'
      path: '/quality-center'
      fullPath: '/quality-center'
      preLoaderRoute: typeof QualityCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webapps': {
      id: '/webapps'
      path: '/webapps'
      fullPath: '/webapps'
      preLoaderRoute: typeof WebappsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-builder': {
      id: '/api/bot-builder'
      path: '/api/bot-builder'
      fullPath: '/api/bot-builder'
      preLoaderRoute: typeof ApiBotBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-edit': {
      id: '/api/bot-edit'
      path: '/api/bot-edit'
      fullPath: '/api/bot-edit'
      preLoaderRoute: typeof ApiBotEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-envio-automatico': {
      id: '/api/bot-envio-automatico'
      path: '/api/bot-envio-automatico'
      fullPath: '/api/bot-envio-automatico'
      preLoaderRoute: typeof ApiBotEnvioAutomaticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-health': {
      id: '/api/bot-health'
      path: '/api/bot-health'
      fullPath: '/api/bot-health'
      preLoaderRoute: typeof ApiBotHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-lifecycle': {
      id: '/api/bot-lifecycle'
      path: '/api/bot-lifecycle'
      fullPath: '/api/bot-lifecycle'
      preLoaderRoute: typeof ApiBotLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-toggle': {
      id: '/api/bot-toggle'
      path: '/api/bot-toggle'
      fullPath: '/api/bot-toggle'
      preLoaderRoute: typeof ApiBotToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-whatsapp': {
      id: '/api/bot-whatsapp'
      path: '/api/bot-whatsapp'
      fullPath: '/api/bot-whatsapp'
      preLoaderRoute: typeof ApiBotWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog-import': {
      id: '/api/catalog-import'
      path: '/api/catalog-import'
      fullPath: '/api/catalog-import'
      preLoaderRoute: typeof ApiCatalogImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog-stock': {
      id: '/api/catalog-stock'
      path: '/api/catalog-stock'
      fullPath: '/api/catalog-stock'
      preLoaderRoute: typeof ApiCatalogStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-admin-user': {
      id: '/api/client-admin-user'
      path: '/api/client-admin-user'
      fullPath: '/api/client-admin-user'
      preLoaderRoute: typeof ApiClientAdminUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/impersonate': {
      id: '/api/impersonate'
      path: '/api/impersonate'
      fullPath: '/api/impersonate'
      preLoaderRoute: typeof ApiImpersonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/magic-onboard': {
      id: '/api/magic-onboard'
      path: '/api/magic-onboard'
      fullPath: '/api/magic-onboard'
      preLoaderRoute: typeof ApiMagicOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provision-status': {
      id: '/api/provision-status'
      path: '/api/provision-status'
      fullPath: '/api/provision-status'
      preLoaderRoute: typeof ApiProvisionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quality-center': {
      id: '/api/quality-center'
      path: '/api/quality-center'
      fullPath: '/api/quality-center'
      preLoaderRoute: typeof ApiQualityCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webapp-factory': {
      id: '/api/webapp-factory'
      path: '/api/webapp-factory'
      fullPath: '/api/webapp-factory'
      preLoaderRoute: typeof ApiWebappFactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/leads': {
      id: '/api/webhooks/leads'
      path: '/api/webhooks/leads'
      fullPath: '/api/webhooks/leads'
      preLoaderRoute: typeof ApiWebhooksLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BotBuilderRoute: BotBuilderRoute,
  ClientsRoute: ClientsRoute,
  HealthRoute: HealthRoute,
  LeadsRoute: LeadsRoute,
  LedgerRoute: LedgerRoute,
  ProductsRoute: ProductsRoute,
  QualityCenterRoute: QualityCenterRoute,
  SettingsRoute: SettingsRoute,
  WebappsRoute: WebappsRoute,
  WebsiteRoute: WebsiteRoute,
  ApiBotBuilderRoute: ApiBotBuilderRoute,
  ApiBotEditRoute: ApiBotEditRoute,
  ApiBotEnvioAutomaticoRoute: ApiBotEnvioAutomaticoRoute,
  ApiBotHealthRoute: ApiBotHealthRoute,
  ApiBotLifecycleRoute: ApiBotLifecycleRoute,
  ApiBotToggleRoute: ApiBotToggleRoute,
  ApiBotWhatsappRoute: ApiBotWhatsappRoute,
  ApiCatalogImportRoute: ApiCatalogImportRoute,
  ApiCatalogStockRoute: ApiCatalogStockRoute,
  ApiClientAdminUserRoute: ApiClientAdminUserRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ApiImpersonateRoute: ApiImpersonateRoute,
  ApiMagicOnboardRoute: ApiMagicOnboardRoute,
  ApiProvisionStatusRoute: ApiProvisionStatusRoute,
  ApiQualityCenterRoute: ApiQualityCenterRoute,
  ApiWebappFactoryRoute: ApiWebappFactoryRoute,
  ApiWebhooksLeadsRoute: ApiWebhooksLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
